# Generated by Django 3.0.2 on 2020-01-19 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20200118_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portal.Area'),
        ),
    ]
