# Generated by Django 3.0.2 on 2020-01-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_auto_20200118_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='descricao',
            field=models.CharField(max_length=200),
        ),
    ]
