# Generated by Django 3.0.2 on 2020-01-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_auto_20200119_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
